In [1]:
import torch

In [2]:
t1=torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
t2=torch.tensor([[1,2,3,4],[5,6,7,8]])

In [5]:
t2+t1

tensor([[ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [6]:
t3=torch.tensor([[[1,2,3,4],[3,4,5,6,]],[[1,2,3,4.],[1,2,3,4]]])

In [7]:
t3.shape

torch.Size([2, 2, 4])

In [8]:
t3=torch.tensor(3.)
t4=torch.tensor(4.,requires_grad=True)
t5=torch.tensor(5.,requires_grad=True)


In [9]:
t6=t4*t3+t5

In [10]:
t6.backward()

In [11]:
print(t6)
print("dy/dx:",t3.grad)
print("dy/dw:",t4.grad)
print("dy/db:",t5.grad)

tensor(17., grad_fn=<AddBackward0>)
dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [12]:
t7=torch.full((3,2),90)

..\aten\src\ATen\native\TensorFactories.cpp:361: UserWarning: Deprecation warning: In a future PyTorch release torch.full will no longer return tensors of floating dtype by default. Instead, a bool fill_value will return a tensor of torch.bool dtype, and an integral fill_value will return a tensor of torch.long dtype. Set the optional `dtype` or `out` arguments to suppress this warning.


In [13]:
t8=torch.sin(t7)

In [14]:
import numpy as np
tx=np.array([[1,2],[3,4]])

In [15]:
ty=torch.from_numpy(np.array([[1,2],[3,4]]))

In [16]:
ty

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [17]:
torch.cuda.is_available()

True

In [18]:
x = torch.Tensor(100).random_(0, 100)
x.to("cuda")

tensor([ 5., 83., 79., 60., 65., 41.,  7., 70., 13., 98., 64., 57., 52., 17.,
        95., 87., 69., 27., 35., 58., 53.,  0., 81., 83., 23., 96., 37., 34.,
        58., 49., 38., 48., 78., 89.,  6., 22.,  7., 85., 50., 70., 65., 65.,
         9., 46., 71., 56., 40., 85., 61.,  0.,  6., 48., 94.,  4., 61., 96.,
        25.,  6.,  0., 72., 77., 57., 59., 70., 67., 45., 45., 74., 77., 48.,
        25., 81., 22., 62., 49., 47., 58., 94., 54., 79., 69.,  3., 42., 19.,
        83.,  0., 69., 27., 51.,  1., 48., 61., 48., 84., 56., 53., 60., 51.,
        37., 78.], device='cuda:0')

In [19]:
r=torch.randn(3,3)
r.to("cuda")

tensor([[-0.3925, -1.0592, -0.3563],
        [-0.0548,  0.4606, -0.2423],
        [ 1.1047,  0.7008, -1.0703]], device='cuda:0')

In [20]:
t=torch.randint(low=0,high=3,size=(3,3)).type(torch.FloatTensor)
t.to("cuda")

tensor([[2., 1., 2.],
        [1., 1., 2.],
        [1., 2., 0.]], device='cuda:0')

In [21]:
a=torch.tensor([3.,4.],requires_grad=True)
b=torch.tensor([4.,5.])
ab=((a + b)**2).sum()


In [22]:
ab.backward()

In [23]:
ab

tensor(130., grad_fn=<SumBackward0>)

In [24]:
input_units=10
output_units=1
hidden_units=100
import torch.nn as nn
model=nn.Sequential(nn.Linear(input_units,hidden_units),\
                    nn.ReLU(),\
                   nn.Linear(hidden_units,output_units),\
                   nn.Sigmoid())


In [25]:
model

Sequential(
  (0): Linear(in_features=10, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=1, bias=True)
  (3): Sigmoid()
)

In [26]:
loss_function=nn.MSELoss()
print(loss_function)

MSELoss()


In [27]:
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)
optimizer

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.01
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [28]:
for i in range(100):
    # Call to the model to perform a prediction
    y_pred = model(x)
    # Calculation of loss function based on y_pred and y
    loss = loss_funct(y_pred, y)
    # Zero the gradients so that previous ones don't accumulate
    optimizer.zero_grad()
    # Calculate the gradients of the loss function
    loss.backward()
    # Call to the optimizer to perform an update of the parameters
    optimizer.step()

RuntimeError: size mismatch, m1: [1 x 100], m2: [10 x 100] at C:\cb\pytorch_1000000000000\work\aten\src\TH/generic/THTensorMath.cpp:41

In [ ]:
import torch
import torch.optim as optim
import matplotlib.pyplot as plt

In [ ]:
x=torch.randn(20,10)
y=torch.randint(0,2,(20,1)).type(torch.FloatTensor)

In [ ]:
optim=optim.Adam(model.parameters(),lr=0.01)

In [ ]:
losses=[]
for i in range(20):
    y_pred=model(x)
    loss=loss_function(y_pred,y)
    losses.append(loss.item())
    optim.zero_grad()
    loss.backward()
    optim.step()
    if i%5==0:
        print(i,loss.item())

In [ ]:
plt.plot(range(0,20),losses)
plt.show()

In [ ]:
import pandas as pd
data=pd.read_csv("https://raw.githubusercontent.com/PacktWorkshops/The-Deep-Learning-with-PyTorch-Workshop/master/Chapter01/Activity1.01/SomervilleHappinessSurvey2015.csv")

In [ ]:
x=torch.tensor(data.iloc[:,1:].values).float()
y=torch.tensor(data.iloc[:,:1].values).float()

In [ ]:
model=nn.Sequential(nn.Linear(6,1),nn.Sigmoid())

In [ ]:
loss_func=torch.nn.MSELoss()

In [ ]:
optimizer=torch.optim.Adam(model.parameters(),lr=0.01)


In [ ]:
losses1=[]
for i in range(100):
    y_pred=model(x)
    #print("y_pred {}".format(y_pred))
    l=loss_function(y_pred,y)
    print(l.item())
    losses1.append(l)
    optimizer.zero_grad()
    l.backward()
    optimizer.step()
    if i%10==0:
        print(l.item())
        

In [ ]:
plt.figure(figsize=(10,8))
plt.plot(range(0,100),losses1)

In [ ]:
losses1

In [ ]:
x={1,2,3,4,5}
sak=list(x)
sak